export enum Action_types {
    GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS',
    GET_PRODUCTS_ERROR= 'GET_PRODUCTS_ERROR',
    GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',

    CREATE_NEW_PRODUCT = 'CREATE_NEW_PRODUCT',
    CREATE_NEW_PRODUCT_ERROR = 'CREATE_NEW_PRODUCT_ERROR',
    CREATE_NEW_PRODUCT_SUCCESS = 'CREATE_NEW_PRODUCT_SUCCESS',
}